name: Terragrunt Plan (Dev)

on:
  pull_request:
    branches:
      - develop

jobs:
  delete_comments:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "write"
    steps:
      - name: Delete bot comments
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}

  build_matrix:
    name: Build Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get all directories in aws/envs folder
        uses: sergeysova/jq-action@v2
        id: find
        with:
          cmd: |
            find aws/envs -type d -maxdepth 3 -mindepth 3 -regex '.*develop' | \
            sed 's|^aws\/envs\/||' |  \
            jq -R -s -c 'split("\n")[:-1]'
      - id: set-matrix
        run: echo 'matrix=${{ steps.find.outputs.value }}' >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  plan:
    runs-on: ubuntu-latest
    needs: [delete_comments, build_matrix]
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    strategy:
      matrix:
        env: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform v1.6.5
        uses: hashicorp/setup-Terraform@v3
        with:
          terraform_version: 1.6.5
          terraform_wrapper: false
          
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Terragrunt v0.45.2 & tools
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.2/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt -v
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          cd aws/envs && tflint --init
          # curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::403372804574:role/infra-reader
          role-session-name: github-actions-role-session
          aws-region: eu-central-1

      - name: Terragrunt format
        run: |-
          cd aws/envs/${{ matrix.env }}
          terragrunt run-all fmt

      - name: Terragrunt validate
        run: |-
          cd aws/envs/${{ matrix.env }}
          terragrunt run-all validate

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.8'

      - name: Compile terraform-j2md
        run: |
          git clone https://github.com/reproio/terraform-j2md.git tool
          (cd tool && make && mv dist/terraform-j2md /usr/local/bin)
          rm -rf tool

      # - name: Install AWS CLI v2
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
      #     unzip -q /tmp/awscliv2.zip -d /tmp
      #     rm /tmp/awscliv2.zip
      #     sudo /tmp/aws/install
      #     rm -rf /tmp/aws/

      # - name: Install GH CLI
      #   uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      #   with:
      #     gh-cli-version: 2.43.1

      - name: Terragrunt plan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: plan
        run: ./scripts/plan.sh "${{ matrix.env }}" "${{ github.event.number }}"