apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ $.Values.secretStore.project }}
      auth:
        workloadIdentity:
          clusterLocation: europe-west4
          clusterName: {{ $.Values.secretStore.clusterName }}
          serviceAccountRef:
            name: external-secret
            namespace: eso