apiVersion: v2
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
type: application

name: kube-prometheus-stack
version: 48.4.1
appVersion: v0.66.0
kubeVersion: ">=1.16.0-0"
keywords:
  - operator
  - prometheus
  - kube-prometheus

dependencies:
  - name: prometheus
    version: "25.30.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled 
  - name: kube-state-metrics
    version: "5.10.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.21.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.58.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: alertmanager
    version: "1.13.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled
