argo-cd:
  crds:
    keep: false

  global:
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists

  redis-ha:
    enabled: true
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists

  controller:
    replicas: 1

  server:
    replicas: 2
    ingress:
      enabled: false
      # annotations: {}
      # controller: generic
      # ingressClassName: ""
      # hostname: ""
      # tls: false

  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2

  dex:
    enabled: true

  notifications:
    enabled: true

  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
