appName: "external-dns"
destNamespace: "external-dns"
destServer: "https://kubernetes.default.svc"
srcPath: "infra/helm-charts/external-dns"
srcRepoURL: "https://github.com/shashwat0309/test-devops-test.git"
srcTargetRevision: "main"
appValues: |
  provider: aws
  aws:
    region: us-west-2
  policy: sync
  logLevel: info
  sources:
    - service
    - ingress
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  rbac:
    create: true
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/external-dns"